In [1]:
import numpy as np
import random

In [47]:
specie = {  # dictionary to relate positions in a 1x3 array to their specie
    0:'A',
    1:'B',
    2:'C',
}
    

def collide(box, x): # x represents the place of the species that will gain 2 more of itself, this function calculates the position after a collision
    N = box[0] + box[1] + box[2]
    places = np.delete(np.array([0,1,2]), x)
    
    if box[places[0]] == 0 or box[places[1]] == 0:
        return box
    
    else: 
        changes = np.zeros(3, dtype=int)
        changes[x] = 2
        
        for i in places:
            changes[i] = -1
        
        box = np.add(box, changes)
        return box

    
def sim(box): # returns the final array from the simulation - either all one species or in a loop for unsolvable
    box = np.array(box)
    # print("The starting box is:", box)
    N = box[0] + box[1] + box[2]
    
    count = 0
    while box.max() < N:
        if np.all(box) == False:
            x = np.argwhere(box==0)[0][0]
        
        else: # i.e. all values non-zero
            x = random.choice([0,1,2])
            
        # print(f"\nParticle in position {x} increases by 2:")
        box = collide(box, x)
        # print("\n", box)
        
        count += 1
        if count == max(1000, N**3):
            # print("It seems this box will not become all the same species\n")
            break
    return box


def print_sim(box): # walks you through the whole simulation of particles colliding and changing
    box = np.array(box)
    print("The starting box is:", box, "\n")
    N = box[0] + box[1] + box[2]
    
    count = 0
    while box.max() < N:
        if np.all(box) == False:
            x = np.argwhere(box==0)[0][0]
        
        else: # i.e. all values non-zero
            x = random.choice([0,1,2])
            
        print(f"Particle in position {x} increases by 2:\n")
        box = collide(box, x)
        print(box, "\n")
        
        count += 1
        if count == N**3:
            print("It seems this box will not become all the same species\n")
            break
    
    return box
    
    
def species(box): # either tells us the final species or returns False for unsolvable
    x = np.argwhere(box==0)
    
    if len(x) == 2:
        index = np.delete(np.array([0,1,2]), x)
        # print("This box becomes all species", specie[index[0]], "\n")
        return specie[index[0]]
    else:
        return False
        

def all_poss_boxes(n, N): # generates all possible combinations for N, n = 3 everytime in our case
    if n == 0:
        if N == 0: return [[]]
        else: return []
    else:
        combos = []
        for i in range(N+1):   # possible last elements
            for j in poss_boxes(n-1,N-i): # solutions for rest of elements
                combos.append(j+[i])
        return combos
    
    
def poss_boxes(N, k, start=None, path=None, result=None): # generates all possible combinations for N, with N_A >= N_B >= N_C,
    if start is None:                                     # n = 3 everytime in our case
        start = N
    if path is None:
        path = []
    if result is None:
        result = []

    if k == 0:
        if sum(path) == N:
            result.append(path[:])
        return 

    for i in range(start, -1, -1):
        if N - i < 0:
            continue
        path.append(i)
        poss_boxes(N, k - 1, i, path, result)
        path.pop()

    return result


def totals(N): # returns the number of solvable and unsolvable combinations, and the total number of combinations
    good = []
    bad = []
    for i in range(len(poss_boxes(N,3))):
        box = np.array(poss_boxes(N,3)[i])
        
        if species(sim(box)):
            good.append(box)
        else:
            bad.append(box)
    
    return len(good), len(bad), len(poss_boxes(N,3))


def group(N): # returns the solvable and unsolvable combinations
    good = []
    bad = []
    for i in range(len(poss_boxes(N,3))):
        box = np.array(poss_boxes(N,3)[i])
        
        if species(sim(box)):
            good.append(box)
        else:
            bad.append(box)
    
    return good, bad

In [19]:
N = 5
good, bad, total = totals(N)
print(f"Out of {total} possible combinations of {N} particles, {good} are solvable, and {bad} are unsolvable")

Out of 5 possible combinations of 5 particles, 5 are solvable, and 0 are unsolvable


In [48]:
M = 6
good, bad, total = totals(M)
print(f"Out of {total} possible combinations of {M} particles, {good} are solvable, and {bad} are unsolvable")

Out of 7 possible combinations of 6 particles, 4 are solvable, and 3 are unsolvable


In [61]:
group(6)     # sorts solvable and unsolvable structures for N=6

([array([6, 0, 0]), array([4, 1, 1]), array([3, 3, 0]), array([2, 2, 2])],
 [array([5, 1, 0]), array([4, 2, 0]), array([3, 2, 1])])

In [74]:
group(18)    # sorts solvable and unsolvable structures for N=18

([array([18,  0,  0]),
  array([16,  1,  1]),
  array([15,  3,  0]),
  array([14,  2,  2]),
  array([13,  4,  1]),
  array([12,  6,  0]),
  array([12,  3,  3]),
  array([11,  5,  2]),
  array([10,  7,  1]),
  array([10,  4,  4]),
  array([9, 9, 0]),
  array([9, 6, 3]),
  array([8, 8, 2]),
  array([8, 5, 5]),
  array([7, 7, 4]),
  array([6, 6, 6])],
 [array([17,  1,  0]),
  array([16,  2,  0]),
  array([15,  2,  1]),
  array([14,  4,  0]),
  array([14,  3,  1]),
  array([13,  5,  0]),
  array([13,  3,  2]),
  array([12,  5,  1]),
  array([12,  4,  2]),
  array([11,  7,  0]),
  array([11,  6,  1]),
  array([11,  4,  3]),
  array([10,  8,  0]),
  array([10,  6,  2]),
  array([10,  5,  3]),
  array([9, 8, 1]),
  array([9, 7, 2]),
  array([9, 5, 4]),
  array([8, 7, 3]),
  array([8, 6, 4]),
  array([7, 6, 5])])

In [64]:
for i in range(len(poss_boxes(4,3))):    # simulation of game for all structures of N=4
    print_sim(poss_boxes(4,3)[i])
    print(f"Finished for box: {poss_boxes(4,3)[i]} \n")

The starting box is: [4 0 0] 

Finished for box: [4, 0, 0] 

The starting box is: [3 1 0] 

Particle in position 2 increases by 2:

[2 0 2] 

Particle in position 1 increases by 2:

[1 2 1] 

Particle in position 1 increases by 2:

[0 4 0] 

Finished for box: [3, 1, 0] 

The starting box is: [2 2 0] 

Particle in position 2 increases by 2:

[1 1 2] 

Particle in position 2 increases by 2:

[0 0 4] 

Finished for box: [2, 2, 0] 

The starting box is: [2 1 1] 

Particle in position 1 increases by 2:

[1 3 0] 

Particle in position 2 increases by 2:

[0 2 2] 

Particle in position 0 increases by 2:

[2 1 1] 

Particle in position 2 increases by 2:

[1 0 3] 

Particle in position 1 increases by 2:

[0 2 2] 

Particle in position 0 increases by 2:

[2 1 1] 

Particle in position 1 increases by 2:

[1 3 0] 

Particle in position 2 increases by 2:

[0 2 2] 

Particle in position 0 increases by 2:

[2 1 1] 

Particle in position 2 increases by 2:

[1 0 3] 

Particle in position 1 increases by 